name: Build & Deploy Game

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/'
      - '.gitignore'
      - '*.md'

env:
  ITCH_IO_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}  # Updated key name
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IS_MAIN: ${{ contains(github.ref, 'main') }}
  GODOT_VERSION: "3.4.3" # Change if needed
  PROJECT_NAME: "The Name Of my Game"  # Insert your project name (human-readable)
  ITCH_PROJECT_NAME: "name-of-my-game" # Insert your project name (key / URL)
  ITCH_USERNAME: "saymyname" # Insert your username!

jobs:
  Build_Exports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ######## Install Godot & Export Templates #########

      - name: Download + Authorize Godot
        run: |
          curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_linux_headless.64.zip
          unzip godot.zip
          mv Godot_v$GODOT_VERSION-stable_linux_headless.64 godot
          chmod +x godot

      - name: Download Export Templates
        run: |
          curl -L -o export_templates.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_export_templates.tpz
          unzip export_templates.zip

      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/templates/$GODOT_VERSION.stable
          mv ./templates/* ~/.local/share/godot/templates/$GODOT_VERSION.stable

      - name: Make Exports & Temp Folder
        run: |
          mkdir exports
          mkdir temp_exports

      - name: Export Web Version
        run: |
          mkdir ./temp_exports/web
          ./godot --path ./project.godot --export "Web" ./temp_exports/web/$PROJECT_NAME.html

      ######## Publish Web Export #########

      - name: Publish Web Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web_export
          path: ./temp_exports/web

  ######## Publish to itch.io #########
  Publish_Exports_To_Itch:
    needs: Build_Exports
    if: ${{ contains(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Web Export
        uses: actions/download-artifact@v3
        with:
          name: web_export
          path: web_export

      - name: Download + Authorize Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Login To Butler
        run: ./butler login

      - name: Push Web Export To Itch
        run: ./butler push ./web_export/$PROJECT_NAME.html $ITCH_USERNAME/$ITCH_PROJECT_NAME:web --userversion-file ./exports/version.txt
