name: Build & Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Download + Authorize Godot
        run: |
          curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
          unzip godot.zip
          mv Godot_v$GODOT_VERSION-stable_linux.x86_64 godot
          chmod +x godot
        env:
          GODOT_VERSION: "4.3"

      - name: Download Export Templates
        run: |
          curl -L -o export_templates.tpz https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_export_templates.tpz
        env:
          GODOT_VERSION: "4.3"

      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/templates/$GODOT_VERSION.stable
          unzip -o export_templates.tpz -d ~/.local/share/godot/templates/$GODOT_VERSION.stable
        env:
          GODOT_VERSION: "4.3"

      - name: Make Export Folders
        run: |
          mkdir -p ./build/web

      - name: Export Web Version
        run: |
          ./godot --headless --path ./melon_game --export-release "web" ./build/web/index.html
        env:
          GODOT_VERSION: "4.3"

      - name: Verify Build
        run: |
          ls -la ./build/web
        # This step helps verify that the web build was successful.

      - name: Butler to Itch
        uses: Ayowel/butler-to-itch@v1.1.0
        with:
          api-key: ${{ secrets.BUTLER_API_KEY }}
          user: ndg8743                           # Your Itch.io username
          game: danmomo-game                      # Your game's slug or name on Itch.io
          channel: web                            # Channel for web deployment
          file: ./build/web                       # Path to the exported web game


# name: Build & Deploy Game

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - '.github/workflows/'
#       - '.gitignore'
#       - '*.md'

# env:
#   ITCH_IO_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}  # Updated key name
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   IS_MAIN: ${{ contains(github.ref, 'main') }}
#   GODOT_VERSION: "4.3" # Change if needed
#   PROJECT_NAME: "Danmomo"  # Insert your project name (human-readable)
#   ITCH_PROJECT_NAME: "https://ndg8743.itch.io/danmomo-game" # Insert your project name (key / URL)
#   ITCH_USERNAME: "ndg8743" # Insert your username!

# jobs:
#   Build_Exports:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source Code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#             ######## Install Godot & Export Templates #########

#       - name: Download + Authorize Godot
#         run: |
#           curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_linux.x86_64.zip
#           unzip godot.zip
#           mv Godot_v$GODOT_VERSION-stable_linux.x86_64 godot
#           chmod +x godot

#       - name: Download Export Templates
#         run: |
#           curl -L -o export_templates.tpz https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_export_templates.tpz

#       - name: Install Export Templates
#         run: |
#           mkdir -p ~/.local/share/godot/templates/$GODOT_VERSION.stable
#           unzip -o export_templates.tpz -d ~/.local/share/godot/templates/$GODOT_VERSION.stable
#           ls ~/.local/share/godot/templates/$GODOT_VERSION.stable  # Confirm the templates are installed
#       - name: Manually Download Web Export Templates
#         run: |
#           mkdir -p ~/.local/share/godot/templates/$GODOT_VERSION.stable
#           curl -L -o ~/.local/share/godot/templates/$GODOT_VERSION.stable/web_nothreads_debug.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/web_nothreads_debug.zip
#           curl -L -o ~/.local/share/godot/templates/$GODOT_VERSION.stable/web_nothreads_release.zip https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/web_nothreads_release.zip
#           ls ~/.local/share/godot/templates/$GODOT_VERSION.stable  # Confirm the templates are installed
#       - name: Make Exports & Temp Folder
#         run: |
#           mkdir exports
#           mkdir temp_exports

#       - name: Export Web Version
#         run: |
#           mkdir ./temp_exports/web
#           ./godot --headless --path ./melon_game --export-release "Web" ./temp_exports/web/index.html
#         ######## Change path names if yours are different^^^^ #########

#       ######## Publish Web Export #########

#       - name: Publish Web Export Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: web_export
#           path: ./temp_exports/web

#   ######## Publish to itch.io #########
#   Publish_Exports_To_Itch:
#     needs: Build_Exports
#     if: ${{ contains(github.ref, 'main') }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download Web Export
#         uses: actions/download-artifact@v3
#         with:
#           name: web_export
#           path: web_export

#       - name: Download + Authorize Butler
#         run: |
#           curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
#           unzip butler.zip
#           chmod +x butler
#           ./butler -V

#       - name: Login To Butler
#         run: ./butler login

#       - name: Push Web Export To Itch
#         run: ./butler push ./web_export/index.html $ITCH_USERNAME/$ITCH_PROJECT_NAME:web --userversion-file ./exports/version.txt